//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginArqut.Domain.Entities
{
    using OriginArqut.Domain.Base;
    using System;
    using System.Collections.Generic;
    
    public partial class Category : IEntity
    {
        public Category()
        {
            this.Product_Category = new HashSet<Product_Category>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Product_Category> Product_Category { get; set; }
    }
}
