//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginArqut.Domain.Entities
{
    using OriginArqut.Domain.Base;
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail : IEntity
    {
        public int Id { get; set; }
        //public int IdOrder { get; set; }
        //public int IdProduct { get; set; }
        public int Count { get; set; }
        public decimal UnitValue { get; set; }
        public decimal TotalValue { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
